# Generated by Django 4.1.7 on 2023-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_created_at_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='home_chef',
            field=models.CharField(default='Home Chef', max_length=200),
        ),
    ]
